-- PostgreSQL schema for SIXTEE SHOP
-- Create the database first: CREATE DATABASE toko;

CREATE TABLE IF NOT EXISTS login (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(200) NOT NULL,
  password varchar(200) NOT NULL,
  email varchar(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS provinsi (
  id_prov varchar(2) PRIMARY KEY,
  nama text NOT NULL,
  ongkir integer NOT NULL
);

INSERT INTO provinsi (id_prov, nama, ongkir) VALUES
  ('11', 'Aceh', 20000), ('12', 'Sumatera Utara', 19500), ('13', 'Sumatera Barat', 19500),
  ('14', 'Riau', 20000), ('15', 'Jambi', 18000), ('16', 'Sumatera Selatan', 19500),
  ('17', 'Bengkulu', 18000), ('18', 'Lampung', 19000), ('19', 'Kepulauan Bangka Belitung', 20000),
  ('21', 'Kepulauan Riau', 20000), ('31', 'DKI Jakarta', 18000), ('32', 'Jawa Barat', 15000),
  ('33', 'Jawa Tengah', 12000), ('34', 'DI Yogyakarta', 12000), ('35', 'Jawa Timur', 10000),
  ('36', 'Banten', 15000), ('51', 'Bali', 20000), ('52', 'Nusa Tenggara Barat', 25000),
  ('53', 'Nusa Tenggara Timur', 25000), ('61', 'Kalimantan Barat', 20000),
  ('62', 'Kalimantan Tengah', 22000), ('63', 'Kalimantan Selatan', 22000),
  ('64', 'Kalimantan Timur', 23000), ('65', 'Kalimantan Utara', 23000),
  ('71', 'Sulawesi Utara', 25000), ('72', 'Sulawesi Tengah', 25000),
  ('73', 'Sulawesi Selatan', 25000), ('74', 'Sulawesi Tenggara', 25000),
  ('75', 'Gorontalo', 22000), ('76', 'Sulawesi Barat', 25000),
  ('81', 'Maluku', 25000), ('82', 'Maluku Utara', 25000),
  ('91', 'Papua Barat', 30000), ('92', 'Papua', 30000)
ON CONFLICT (id_prov) DO NOTHING;

CREATE TABLE IF NOT EXISTS tb_admin (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(30) NOT NULL,
  password varchar(30) NOT NULL,
  nama varchar(30) NOT NULL
);

INSERT INTO tb_admin (username, password, nama)
SELECT 'admin', 'admin123', 'Administrator'
WHERE NOT EXISTS (SELECT 1 FROM tb_admin WHERE username = 'admin');

CREATE TABLE IF NOT EXISTS tb_pelanggan (
  id_pelanggan integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  password text NOT NULL,
  nama_pelanggan text NOT NULL,
  telepon text NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_produk (
  id_produk integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_produk varchar(40) NOT NULL,
  harga_produk integer NOT NULL,
  berat_produk integer NOT NULL,
  foto_produk varchar(40) NOT NULL,
  deskripsi_produk text NOT NULL
);

INSERT INTO tb_produk (nama_produk, harga_produk, berat_produk, foto_produk, deskripsi_produk)
SELECT * FROM (VALUES
  ('Baju Kemeja Levis', 255000, 1000, 'baju1.jpg', 'Kemeja kasual berkualitas dengan desain klasik untuk aktivitas sehari-hari.'),
  ('Celana Jeans', 175000, 200, 'celana1.jpg', 'Celana jeans nyaman dengan potongan modern dan mudah dipadukan.'),
  ('Jam Tangan', 250000, 50, 'jam tangan.jpg', 'Jam tangan bergaya yang cocok untuk melengkapi penampilan harian.'),
  ('Tali Pinggang', 50000, 100, 'ikatpinggang.jpg', 'Tali pinggang kuat dan praktis dengan tampilan minimalis.'),
  ('Koleksi Pilihan', 1200000, 1200, '22.jpg', 'Produk pilihan dengan kualitas terbaik untuk kebutuhan Anda.')
) AS produk(nama_produk, harga_produk, berat_produk, foto_produk, deskripsi_produk)
WHERE NOT EXISTS (SELECT 1 FROM tb_produk);

CREATE TABLE IF NOT EXISTS tb_pembelian (
  id_pembelian integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pelanggan integer NOT NULL,
  id_prov varchar(2) NOT NULL,
  kabupaten text NOT NULL DEFAULT '',
  kecamatan text NOT NULL DEFAULT '',
  tanggal_pembelian date NOT NULL,
  total_pembelian integer NOT NULL,
  tarif integer NOT NULL,
  alamat varchar(50) NOT NULL,
  status varchar(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_pembelian_produk (
  id_pembelian_produk integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pembelian integer NOT NULL,
  id_produk integer NOT NULL,
  jumlah integer NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_pembayaran (
  id_pembayaran integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pembelian integer NOT NULL,
  nama varchar(30) NOT NULL,
  bank varchar(30) NOT NULL,
  jumlah integer NOT NULL,
  tanggal date NOT NULL,
  bukti varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ulasan (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rating integer NOT NULL,
  coment text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pembelian_pelanggan ON tb_pembelian (id_pelanggan);
CREATE INDEX IF NOT EXISTS idx_pembelian_produk_pembelian ON tb_pembelian_produk (id_pembelian);
CREATE INDEX IF NOT EXISTS idx_pembayaran_pembelian ON tb_pembayaran (id_pembelian);
